### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by Serfentum** [horvatovichlab/MSIWarp#5]
Hi!
Unfortunately, I have an error when  trying to install MSIWrap. Here are the commands which I've used
```
git clone --recursive https://github.com/horvatovichlab/MSIWarp.git
python3 setup.py install --user
```

Here is the output
```
/home/a.ilin/anaconda3/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was impor
ted before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptoo
ls' objects directly or at least import Setuptools first.
  warnings.warn(
running install
running bdist_egg
running egg_info
writing src/python-bindings/msiwarp.egg-info/PKG-INFO
writing dependency_links to src/python-bindings/msiwarp.egg-info/dependency_links.txt
writing requirements to src/python-bindings/msiwarp.egg-info/requires.txt
writing top-level names to src/python-bindings/msiwarp.egg-info/top_level.txt
writing top-level names to src/python-bindings/msiwarp.egg-info/top_level.txt                              
reading manifest file 'src/python-bindings/msiwarp.egg-info/SOURCES.txt'
writing manifest file 'src/python-bindings/msiwarp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features                                                                         
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- pybind11 v2.6.1 dev1
-- Configuring done
CMake Error in CMakeLists.txt:
  Target "msiwarp" requires the language dialect "CXX17" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.


CMake Error in CMakeLists.txt:
  Target "warplib" requires the language dialect "CXX17" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "setup.py", line 62, in <module>                                                                    
    setup(
  File "/home/a.ilin/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/a.ilin/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/a.ilin/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_instal
l
    self.run_command('bdist_egg')
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/a.ilin/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 174, in r
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/a.ilin/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 160, in call_comman
d
    self.run_command(cmdname)
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/a.ilin/anaconda3/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/a.ilin/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 32, in run                                                                          self.build_extension(ext)
  File "setup.py", line 56, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args,
  File "/home/a.ilin/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/a.ilin/soft/MSIWarp', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/hom
e/a.ilin/soft/MSIWarp/build/lib.linux-x86_64-3.8/msiwarp', '-DPYTHON_EXECUTABLE=/home/a.ilin/anaconda3/bin/python', '
-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

My version of CMake is 3.17.2. I've briefly looked over the stack and came across [this link](https://stackoverflow.com/questions/47238577/target-requires-the-language-dialect-cxx17-with-compiler-extensions-but-cma) where g++ update was proposed. My g++ version is 4.8.5, can it be the problem? If so, I'll ask our sysadmin to update it 
Thank you in advance)

**Comment by j-o-eriksson** [comment]
Hi, sorry for the late reply. As you suggest, your g++ version is too low. MSIWarp requires C++ 17 support. Hope your sysadmin was able to sort it out.
Best!
